# Generated by Django 4.0.2 on 2022-03-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_member_email_alter_member_rank_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone',
            new_name='phone_name',
        ),
    ]
