# Generated by Django 4.0.2 on 2022-03-03 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_phone_member_phone_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='phone_name',
            new_name='phone_number',
        ),
    ]
